server:
  port: 7011
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
eureka:
  client:
    service-url:
      defaultZone: http://root:root123@localhost:7776/eureka/
logging:
  level: info
spring:
  application:
    name: hlx_dm-user-provider
  datasource:
    url: jdbc:mysql://localhost:3306/dm_user?useUnicode=true&characterEncoding=gbk&zeroDateTimeBehavior=convertToNull
    username: root
    password: root123
    driver-class-name: com.mysql.jdbc.Driver
