spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/dm_base?useUnicode=true&characterEncoding=gbk&zeroDateTimeBehavior=convertToNull
    username: root
    password: root123
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: hlx_dm-base-provider
eureka:
  client:
    service-url:
      defaultZone: http://root:root123@localhost:7776/eureka/
moduleName: hlx_dm-base-provider
server:
  port: 7002
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
