spring:
  kafka:
    producer:
      bootstrap-servers: 192.163.50.130:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
