spring:
  application:
    name: hlx_dm-testDemo
  datasource:
    url: jdbc:mysql://localhost:3306/dm_user?useUnicode=true&characterEncoding=gbk&zeroDateTimeBehavior=convertToNull
    username: root
    password: root123
    driver-class-name: com.mysql.jdbc.Driver
eureka:
  client:
    service-url:
      defaultZone: http://root:root123@localhost:7776/eureka/
moduleName: hlx_dm-testDemo
server:
  port: 7015



